# Generated by Django 3.2 on 2021-04-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_bye',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
