# Generated by Django 3.2 on 2021-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210421_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
