# Generated by Django 3.2 on 2021-04-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_project_completed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_bye',
            new_name='created_by',
        ),
    ]
