# Generated by Django 3.2 on 2021-04-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_created_bye_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/project_files/% Y/% m/% d/'),
        ),
    ]
