# Generated by Django 3.2 on 2021-04-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210422_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/task_files'),
        ),
    ]
