# Generated by Django 3.2 on 2021-04-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_bankinfo_personalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinfo',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.bankinfo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.personalinfo'),
        ),
    ]
