# Generated by Django 3.2 on 2021-04-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210424_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('marks', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='WorkExpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=13, null=True)),
                ('relation', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateField(blank=True, max_length=30, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pri_contact_num', models.CharField(blank=True, max_length=13, null=True)),
                ('pri_contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pri_contact_relation', models.CharField(blank=True, max_length=30, null=True)),
                ('sec_contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sec_contact_num', models.CharField(blank=True, max_length=30, null=True)),
                ('sec_contact_relation', models.CharField(blank=True, max_length=30, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.employee')),
            ],
        ),
    ]
