# Generated by Django 3.2 on 2021-04-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210424_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='employee',
        ),
    ]
