# Generated by Django 3.2 on 2021-04-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_emergencycontact_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.emergencycontact'),
        ),
    ]
