# Generated by Django 3.2 on 2021-04-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_employee_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduinfo',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.employee'),
        ),
    ]
