# Generated by Django 3.2 on 2021-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_eduinfo_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatar.jpeg', null=True, upload_to='employee/profile_pic'),
        ),
    ]
